const fs = require("fs");
const path = require("path");
const { softBlockedSites } = require("./entitlement");
const { policy } = require("./catalog");
const logger = require("./logger");

function traefikDynamicPath() {
  return (
    process.env.SITE_BILLING_TRAEFIK_DYNAMIC_PATH ||
    "/opt/services/infra/traefik/dynamic/billing-blocks.yml"
  );
}

function billingServiceUrl() {
  return (
    process.env.SITE_BILLING_TRAEFIK_SERVICE_URL ||
    "http://site-billing:3021"
  );
}

function hostRule(hosts) {
  return hosts.map((h) => `Host(\`${h}\`)`).join(" || ");
}

/**
 * Write Traefik file-provider config that steals Host traffic for soft-blocked
 * sites and serves the paused page from site-billing.
 *
 * When nothing is blocked, delete the file — Traefik rejects empty
 * `middlewares: {}` / `routers: {}` maps as invalid standalone elements.
 */
function renderBlocksYaml(sites) {
  const serviceUrl = billingServiceUrl();
  const contact = policy().contactEmail;

  if (!sites.length) {
    return null;
  }

  const lines = [
    "# Generated by site-billing — do not edit by hand",
    `# contact: ${contact}`,
    "http:",
    "  middlewares:",
    "    billing-paused-path:",
    "      replacePath:",
    "        path: /paused",
    "  services:",
    "    site-billing-paused:",
    "      loadBalancer:",
    "        servers:",
    `          - url: "${serviceUrl}"`,
    "  routers:",
  ];

  for (const site of sites) {
    const hosts = site.hosts || [];
    if (!hosts.length) continue;
    const name = `billing-block-${site.id}`.replace(/[^a-zA-Z0-9-_]/g, "-");
    lines.push(`    ${name}:`);
    lines.push(`      rule: ${hostRule(hosts)}`);
    lines.push("      entryPoints:");
    lines.push("        - web");
    lines.push("      service: site-billing-paused");
    lines.push("      middlewares:");
    lines.push("        - billing-paused-path");
    // Beat Docker-provider defaults (priority ≈ rule length).
    lines.push("      priority: 100000");
  }

  lines.push("");
  return lines.join("\n");
}

function applyTraefikBlocks() {
  const blocked = softBlockedSites().filter((s) => (s.hosts || []).length);
  const yaml = renderBlocksYaml(blocked);
  const file = traefikDynamicPath();
  const dir = path.dirname(file);
  fs.mkdirSync(dir, { recursive: true });

  if (!yaml) {
    if (fs.existsSync(file)) {
      fs.unlinkSync(file);
    }
    logger.info("traefik_blocks_cleared", { path: file });
    return { path: file, blocked: [] };
  }

  const tmp = `${file}.tmp`;
  fs.writeFileSync(tmp, yaml);
  fs.renameSync(tmp, file);
  logger.info("traefik_blocks_written", {
    path: file,
    blocked: blocked.map((s) => s.id),
  });
  return { path: file, blocked: blocked.map((s) => s.id) };
}

module.exports = {
  traefikDynamicPath,
  billingServiceUrl,
  hostRule,
  renderBlocksYaml,
  applyTraefikBlocks,
};
