services:
  beyond-the-bell:
    image: ghcr.io/r2pen2/wl-universe-beyond-the-bell:pr-42
    container_name: qa-pr-42-beyond-the-bell
    restart: "no"
    env_file:
      - /opt/services/data/app-env/qa/beyond-the-bell.env
    environment:
      PORT: "3000"
      CMS_COLLECTION_PREFIX: "qa-pr-42-"
    volumes:
      - /opt/services/data/app-assets/beyond-the-bell/static:/repo/packages/beyond-the-bell/static:ro
      - /opt/services/data/app-assets/beyond-the-bell/images:/repo/packages/beyond-the-bell/images:ro
      - /opt/services/data/app-env/beyond-the-bell-serviceAccountKey.json:/repo/packages/beyond-the-bell/config/serviceAccountKey.json:ro
    networks:
      - proxy
    labels:
      com.centurylinklabs.watchtower.enable: "false"
      traefik.enable: "true"
      traefik.http.routers.qa-pr-42-beyond-the-bell.rule: Host(`pr-42-beyond-the-bell.joed.dev`)
      traefik.http.routers.qa-pr-42-beyond-the-bell.entrypoints: web
      traefik.http.services.qa-pr-42-beyond-the-bell.loadbalancer.server.port: "3000"

networks:
  proxy:
    external: true
